apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
# YAML patch not needed with kpt, uses setter instead
# patchesStrategicMerge:
# - replica_count.yaml
namespace: staging
namePrefix: staging-
commonLabels:
  environment: staging
