apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesStrategicMerge:
- replica_count.yaml
namespace: staging
namePrefix: staging-
commonLabels:
  environment: staging